# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://juyoungbang.github.io
title: Juyoung Bang
email: juyoungbang@unist.ac.kr
author: Juyoung Bang
description: Homepage of Juyoung Bang
copyright: 'Copyright &copy; 2021 Juyoung Bang. All Rights Reserved.'
credits: 'Credits: Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: email
    url: mailto:juyoungbang@unist.ac.kr
  - title: github
    url: https://github.com/juyoungbang
  - title: facebook
    url: https://www.facebook.com/profile.php?id=100006305915123